export const QUESTION_UPDATE = 'QUESTION_UPDATE'

export const RESULTS_UPDATE = 'RESULTS_UPDATE'

export const OPTIONS_SELECTED_UPDATE = 'OPTIONS_SELECTED_UPDATE'
export const OPTIONS_SELECTED_RESET = 'OPTIONS_SELECTED_RESET'